properties
# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
# Android/AndroidX
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
# React Native
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=true
hermesEnabled=true
# UI/Display
edgeToEdgeEnabled=true
# Expo Specifics
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
expo.useLegacyPackaging=false
# Debugging
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
# REMOVE THIS in SDK 55
expo.edgeToEdgeEnabled=true 