properties
kotlin.incremental=true
# Only if your project doesn't use native BuildConfig or generated resource values
# android.defaults.buildfeatures.buildConfig=false
# android.defaults.buildfeatures.resValues=false