properties
# Development architectures (Fast build). 
# For production/release, either comment this out or use: ./gradlew assembleRelease -PreactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
reactNativeArchitectures=arm64-v8a,x86_64