properties
# UI/Display
# This is the standard RN/Android flag
edgeToEdgeEnabled=true
# REMOVE THIS in SDK 55 - Keep it here only until you upgrade
expo.edgeToEdgeEnabled=true properties
# UI/Display
# This is the standard RN/Android flag
edgeToEdgeEnabled=true
# REMOVE THIS in SDK 55 - Keep it here only until you upgrade
expo.edgeToEdgeEnabled=true