services:
  - type: web
    name: mitralink-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: mitralink_secret_2026
      - key: GROQ_API_KEY
        fromContext: git
      - key: GEMINI_API_KEY
        fromContext: git
      - key: GEMINI_API_KEY
        fromContext: git
